# Generated by Django 5.0.4 on 2024-04-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='stock',
        ),
    ]
