# Generated by Django 5.0.4 on 2024-04-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stocks_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laborname', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('salarystatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(max_length=10)),
                ('products', models.ManyToManyField(to='core.stock')),
                ('client', models.ManyToManyField(to='core.client')),
            ],
        ),
    ]
