# Generated by Django 5.0.4 on 2024-04-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_labor_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='productname',
            field=models.CharField(db_index=True, max_length=70),
        ),
    ]
