# Generated by Django 5.0.4 on 2024-04-23 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bill_products_delete_billproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billno',
        ),
        migrations.AddField(
            model_name='bill',
            name='billdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='billstatus',
            field=models.BooleanField(default=False),
        ),
    ]
