# Generated by Django 5.0.4 on 2024-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bill_billno_bill_billdate_bill_billstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='grandtotal',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
