# Generated by Django 5.0.4 on 2024-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bill_grandtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='maximumstock',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
