# Generated by Django 5.0.4 on 2024-04-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stock_maximumstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='client',
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
    ]
