# Generated by Django 5.0.4 on 2024-04-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_bill_client_bill_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='grandtotal',
            new_name='billno',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='billdate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='billstatus',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
    ]
