# Generated by Django 5.0.4 on 2024-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_stock_maximumstock_alter_stock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='day_wage',
            field=models.PositiveIntegerField(blank=True, default=645),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labor',
            name='salary_amount',
            field=models.PositiveBigIntegerField(blank=True, default=20000),
            preserve_default=False,
        ),
    ]
