# Generated by Django 5.0.4 on 2024-04-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_labor_day_wage_labor_salary_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='salarymanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentdays', models.PositiveIntegerField(blank=True, default=0)),
                ('salarydue', models.PositiveIntegerField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labor')),
            ],
        ),
    ]
