# Generated by Django 5.0.4 on 2024-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_salarymanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billstatus',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
