# Generated by Django 5.0.4 on 2024-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bill_billstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarymanagement',
            name='withdrawal',
            field=models.TextField(blank=True),
        ),
    ]
