# Generated by Django 5.0.4 on 2024-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_salarymanagement_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymanagement',
            name='transaction',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
